import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PrimeSSRProvider from "@/providers/prime-ssr-provider";

import "./globals.css";
import { Footer } from "@/components/footer";
import Header from "@/components/header";
import { WhatsappButton } from "@/components/whatsapp-button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ colorScheme: "light" }}>
      <head>
        <meta name="color-scheme" content="light" />
        <meta name="theme-color" content="#ffffff" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
        style={{ colorScheme: "light" }}
      >
        <PrimeSSRProvider>
          <Header />
          {children}
          <Footer />
          <WhatsappButton />
        </PrimeSSRProvider>
      </body>
    </html>
  );
}
